config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "payments#new"
  resources :payments

  post "/payments/stripe" => "payments#stripe", :as => :payments_stripe
  post "/payments/stripe_checkout" => "payments#stripe_checkout", :as => :stripe_checkout

  get "/stripe_success" => "payments#stripe_success", :as => :stripe_success
  get "/stripe_cancel" => "payments#stripe_cancel", :as => :stripe_cancel

  get "/stripe_session_status" => "payments#stripe_session_status", :as => :stripe_session_status

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end
  
  def create
    environment = PayPal::SandboxEnvironment.new(ENV['PAYPAL_CLIENT_ID'], ENV['PAYPAL_SECRET'])
    # environment = PayPal::SandboxEnvironment.new('AeHFJN2Mxov18fzGnkK250reMc7h1oP0vZrnoL6zDL2RJu6gk3hJMdfVqgVbDhrr_h6tgJlb08nV-__W', 'EGTYPz6iRoPcf0hU099tr4cqipb2MRIEl_pSljOLxyusKsbvqWHVTnXPLx7mCBra4CugpOpIAWqwbLIR')
    client = PayPal::PayPalHttpClient.new(environment)
    request = PayPalCheckoutSdk::Orders::OrdersCaptureRequest::new(params[:order_id])
    begin
      # Call API with your client and get a response for your call
      response = client.execute(request)
      # If call returns body in response, you can get the deserialized version from the result attribute of the response
      order = response.result
      Payment.create order_id: order.id, payer_id: order.payer.payer_id
    rescue PayPalHttp::HttpError => ioe
      # Something went wrong server-side
      puts ioe.status_code
      puts ioe.headers["debug_id"]
    end
  end




  # stripe
  def stripe
    # Set your Stripe API key
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    
    # Get the token from the request
    token = params[:stripeToken]

    # Create a charge: this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        amount: 1000, # amount in cents
        currency: 'usd',
        source: token,
        description: 'Example Charge'
      )

      flash[:notice] = "Payment successfully stripe"
      redirect_to root_path
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
    end
  end


  def stripe_checkout
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          currency: 'usd',
          product_data: {
            name: 'T-Shirt',
          },
          unit_amount: 200,
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url: 'http://localhost:3000/stripe_success?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: 'http://localhost:3000/stripe_cancel?session_id={CHECKOUT_SESSION_ID}',
    )
    redirect_to session.url, status: 303, allow_other_host: true
  end

  def show
    render plain: "thanh toán"
  end

  def stripe_success
    payment_session_id = params[:session_id]
    session = Stripe::Checkout::Session.retrieve(payment_session_id)
    
    render json: {status: session.status, msg: 'Thành Công', session: session}
    # render plain: "thanh toán thành công"
  end

  def stripe_cancel
    payment_session_id = params[:session_id]
    session = Stripe::Checkout::Session.retrieve(payment_session_id)
    
    render json: {status: session.status, msg: 'Cancel', session: session}
    # render plain: "thanh toán cancel"
  end

  # stripe
  def stripe_session_status
    payment_session_id = params[:session_id]
    session = Stripe::Checkout::Session.retrieve(payment_session_id)
    
    render json: {status: session.status, session: session}
  end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paypal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> -->
    <%= stylesheet_link_tag "application" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbo="false">
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<script src="https://www.paypal.com/sdk/js?client-id=<%= ENV['PAYPAL_CLIENT_ID'] %>"></script>

<h2>Paypal</h2>

<a href='https://www.sandbox.paypal.com/' style='font-size: 20px' target='_blank'>Tài khoản sanbox</a>
<br>
<br>

<div id="paypal-button-container"></div>



<h2>Stripe</h2>
<a href='https://stripe.com/docs/testing?locale=en-GB#testing-interactively' style='font-size: 20px' target='_blank'>Tài khoản sanbox</a>
<br>
<br>
<%= button_to "Buy with stripe checkout", stripe_checkout_path, method: :post, style: 'font-size: 20px' %>

<br>
<p>Stripe js</p>
<%= form_tag payments_stripe_path do %>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
    data-amount="1000"
    data-name="Sample Charge"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-currency="usd">
  </script>
<% end %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<script>
  paypal.Buttons({
    createOrder: function (data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            "currency_code": "USD",
            value: '1'
          }
        }]
      });
    },
    onApprove: function (data, actions) {
        $.ajax({
            url: '<%= payments_path %>',
            method: 'POST',
            dataType: 'json',
            data: JSON.stringify({
              'order_id': data.orderID,
              'payer_id': data.payerID
            }),
            headers: {
              'Content-Type': 'application/json',
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
        }).then(function () {
            alert("Thanh toán thành công!");
        });
      
    },
    onCancel(data) {
      // Show a cancel page, or return to cart
      console.log("cancel");
    },
    onError(err) {
      // For example, redirect to a specific error page
      console.log(err);
      window.location.href = "/";
    }
  }).render('#paypal-button-container');
</script>